name: AgriCam Pipeline

on:
  push:
    branches: [main]

jobs:

  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-3
      TF_VAR_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      TF_VAR_environnement: dev

    defaults:
      run:
        working-directory: environnements/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform fmt -check

      - run: terraform validate

      - run: terraform plan

      - run: terraform apply -auto-approve